theme: minima
title: My Learning Journal
author: laulujan
email: lauralujanhdez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is my learning journal as a participant of the Encora Academy 2021a generation. Here I'll keep a log on what I learn on my way to becoming a software engineer.

# social links
twitter_username: laudotdot # DO NOT include the @ character, or else the build will fail!
github_username:  laulujan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
